server:
  port: 8090

spring:
  application:
    name: spring_security

  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa:
#    show-sql: true
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate.format_sql: true
  h2:
    console:
      enabled: true
      path: /console/